name: PyInstaller Build

on:
  push:
    branches: ["main"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5

    - name: install PyInstaller
    - uses: actions/bash installThings@v3
    
