# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: build with PyInstaller
      run: |
        pyinstaller -n pyplayer -y newnewmain.py

    - name: Move Images Folder over
      run: |
        cp -r ./images dist/pyplayer/images

    - name: Push dist to gh
      run: |
        git add ./dist/*
        git config user.name "$GITHUB_ACTOR"
        git config user.email "$GITHUB_ACTOR@no-reply.github.com"
        git commit -m "[skip ci] pushed release"
        git push origin master
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
